sudo: false
language:
  - python
python:
  - "3.5"
env:
  - NODE_VERSION="6.9"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
before_install:
  - nvm install $NODE_VERSION
install:
  - make deps
jobs:
  include:
    - name: "Test"
      before_install:
        - pip install codecov
      script: make test
      after_success:
        - codecov
    - name: "Lint"
      script: make lint
