sudo: false
language:
  - python
python:
  - "3.6"
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install: pip install tox tox-pip-extensions
jobs:
  include:
    - name: "Test"
      script: make test
      after_success: make coverage codecov
    - name: "Lint"
      script: make lint
    - name: "Check formatting"
      script: make checkformatting
